#spring.application.name=pruebaWhatsApp2
#
#server.port=8081
#
#
#evolution.url=http://127.0.0.1:8080
#evolution.apikey=BQYHJGJHJ
#evolution.instance=jrdev
#
#
#whatsapp.test.number=18494782488


#whatsapp platform
spring.application.name=pruebaWhatsApp2
server.port=8081

# =====================================================
# DATABASE - SUPABASE
# =====================================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

# =====================================================
# EVOLUTION API
# =====================================================

evolution.url=http://127.0.0.1:8080
evolution.apikey=${EVOLUTION_API_KEY}

# =====================================================
# WHATSAPP
# =====================================================

whatsapp.test.number=18494782488