
#whatsapp platform
spring.application.name=whatsapp-platform
server.port=${PORT:8081}

# =====================================================
# Configuracion de Redis
# =====================================================

spring.data.redis.host=20.63.24.170
spring.data.redis.port=6379
spring.data.redis.password=@redis08112026jrdev


# =====================================================
# DATABASE - SUPABASE
# =====================================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

# =====================================================
# EVOLUTION API
# =====================================================

evolution.url=http://20.63.24.170:8080
evolution.apikey=${EVOLUTION_API_KEY}

# =====================================================
# WHATSAPP
# =====================================================

whatsapp.test.number=18494782488